# Generated by Django 3.2.17 on 2023-02-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lost_credit',
            field=models.IntegerField(default=2000),
        ),
    ]
