# Generated by Django 3.2.16 on 2023-05-27 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('name', models.TextField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
            ],
        ),
    ]
