from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from pc.views import *


app_name = 'pc'
urlpatterns = [
    path('', home, name='home'),
    path(
        'login/',
        LoginView.as_view(template_name='login.html'),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='logged_out.html'),
        name='logout'
    ),
    path(
        'signup/',
        SignUp.as_view(),
        name='signup'
    ),
    path(
        'add_collector/<int:id>/',
        add_collector,
        name='add_collector'
    ),
    path(
        'collector_orders/',
        collector_orders,
        name='collector_orders'
    ),
    path(
        'set_assembled/<int:id>/',
        set_assembled,
        name='set_assembled'
    ),
    path(
        'history_orders/',
        history_orders,
        name='history_orders'
    ),
    path(
        'salary/',
        salary,
        name='salary'
    ),
    path(
        'analise_order/',
        analise_order,
        name='analise_order'
    ),
    path(
        'add_shoppinglist/<int:id>/',
        add_shoppinglist,
        name='add_shoppinglist'
    ),
    path(
        'basket/',
        basket,
        name='basket'
    ),
    path(
        'plus_count/<int:id>/',
        plus_count,
        name='plus_count'
    ),
    path(
        'minus_count/<int:id>/',
        minus_count,
        name='minus_count'
    ),
    path(
        'del_shop_item/<int:id>/',
        del_shop_item,
        name='del_shop_item'
    ),
    path(
        'add_order/',
        add_order,
        name='add_order'
    ),
    path(
        'user_order/',
        user_order,
        name='user_order'
    ),
    path(
        'view_cheque/<int:id>/',
        view_cheque,
        name='view_cheque'
    )
]
