# Generated by Django 4.1.7 on 2023-05-15 11:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Минимальная цена - 1')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='pc.group')),
            ],
            options={
                'verbose_name': 'Комплектующие',
                'verbose_name_plural': 'Комплектующие',
            },
        ),
    ]
