# Generated by Django 4.1.7 on 2023-05-15 11:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Наряд на сборку',
                'verbose_name_plural': 'Наряды на сборку',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='accessories',
            options={'verbose_name': 'Комплектующее', 'verbose_name_plural': 'Комплектующие'},
        ),
        migrations.AddField(
            model_name='accessories',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessories',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='pc.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Минимальная цена - 1')], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='AssemblyOrderAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Минимальное количество - 1')], verbose_name='Количество')),
                ('assembly_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.assemblyorder', verbose_name='Наряд на сборку')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.accessories', verbose_name='Комплектующее')),
            ],
            options={
                'verbose_name': 'Ингредиент-рецепт',
                'verbose_name_plural': 'Ингредиенты-рецепты',
            },
        ),
        migrations.AddField(
            model_name='assemblyorder',
            name='accessories',
            field=models.ManyToManyField(through='pc.AssemblyOrderAccessories', to='pc.accessories', verbose_name='Комплектующие'),
        ),
        migrations.AddField(
            model_name='assemblyorder',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_orders', to=settings.AUTH_USER_MODEL, verbose_name='Сборщик'),
        ),
    ]
