# Generated by Django 4.1.7 on 2023-05-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0004_alter_assemblyorder_collector'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyorder',
            name='name',
            field=models.CharField(default=1, max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
