# Generated by Django 4.1.7 on 2023-05-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0005_assemblyorder_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assemblyorderaccessories',
            old_name='ingredient',
            new_name='accessories',
        ),
    ]
