# Generated by Django 4.1.7 on 2023-05-15 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pc', '0007_alter_assemblyorderaccessories_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyorder',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assemblyorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
    ]
