# Generated by Django 4.1.7 on 2023-05-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0008_assemblyorder_confirmation_assemblyorder_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblyorderaccessories',
            options={'default_related_name': 'assembly_order_accessories', 'verbose_name': 'Комплектующее', 'verbose_name_plural': 'Комплектующие'},
        ),
    ]
