# Generated by Django 4.1.7 on 2023-05-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0009_alter_assemblyorderaccessories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyorder',
            name='assembled',
            field=models.BooleanField(default=False),
        ),
    ]
