# Generated by Django 4.1.7 on 2023-05-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc', '0010_assemblyorder_assembled'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyorder',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
