# Generated by Django 4.1.7 on 2023-05-17 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pc', '0015_alter_shoppinglist_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblyorderaccessories',
            options={'default_related_name': 'assembly_order_accessories', 'verbose_name': 'Комплектующее - Наряд на сборку', 'verbose_name_plural': 'Комплектующие - Наряды на сборку'},
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='accessories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pc.accessories', verbose_name='Комплектующее'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
